config/routes.rb
Rails.application.routes.draw do
  resources :polls

    post "/polls/:id", to: 'ballots#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ballot.rb
class Ballot < ApplicationRecord
  belongs_to :poll
  has_many :ranks
  validate :ranks_are_ordered_correctly

  def ranks_are_ordered_correctly
    unless self.ranks.map{ |r| r.score }.sort == (1..self.poll.options.count).to_a
      errors.add(:base, "Ranks aren't ordered properly")
    end
  end
end

app/models/instant_runoff.rb
class InstantRunoff

  def initialize(poll)
    @poll = poll.deep_clone(include: {ballots: :ranks})
    @ranks = @poll.ballots.map(&:ranks).flatten
    @losers = []
  end

  def winner
    @winner = recursively_vote(@ranks).first.option.name
  end

  private

  def get_loser(ranks)
    # Select all ranks with score = 1 and create a list of the associated names
    list = ranks.select { |r| r.score == 1 }.map { |r| r.option.name }

    # If anyone option has zero votes with rank 1 it should be the loser
    # So we check if any option has no ranks with score = 1
    unique_options = ranks.map { |r| r.option.name }.uniq
    bad_losers = unique_options - (unique_options & list)
    # if there are any options with no rank = 1 then one of these is the loser
    return bad_losers.first if bad_losers.present?

    # select the option which received the fewest votes with rank = 1 (the loser)
    list.group_by(&:itself)
      .map {|option, count| [option, count]}
      .sort_by { |e| e[1].length}
      .first
      .first
  end

  def remove_loser(ranks)
    loser = get_loser(ranks)
    @losers.push(loser)
    # Redefine ranks as all those except the losers
    ranks.select {|r| r.option.name != loser}
  end

  def bump_remaining_votes(ballots, ranks)
    # close gaps in each ballot (e.g. no ballot should look like [0,1,3,4])
    #show remaining ballots
    result = ballots.map do |ballot|
      remaining_ranks = ballot.ranks.select{ |rank| ranks.include?(rank) }
      remaining_ranks.sort_by! { |rank| rank.score }
      remaining_ranks.reduce do |acc, rank|
        unless rank.score == acc.score + 1
          rank.score -= 1
          rank.save
        end
        acc = rank
      end
      remaining_ranks
    end
    return result.flatten
  end

  def only_one_left(ranks)
    list = ranks.map{ |r| r.option.name }
    list.uniq.length == 1
  end

  def recursively_vote(ranks)
    return ranks if only_one_left(ranks)
    ranks = bump_remaining_votes(@poll.ballots, ranks)
    recursively_vote(remove_loser(ranks))
  end

end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :poll
  has_many :ranks
end

app/models/poll.rb
class Poll < ApplicationRecord
  has_many :options
  has_many :ballots
  has_many :ranks, through: :ballots
end

app/models/rank.rb
class Rank < ApplicationRecord
  belongs_to :ballot
  belongs_to :option
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/ballots_controller.rb
class BallotsController < ApplicationController

  def create
    poll = Poll.find(params.require(:id))
    @ballot = Ballot.new(ballot_params)
    @ballot.poll = poll
    @ballot.ranks = poll.options.map do |o|
      Rank.new(score: params[o.name + '_score'], option: o)
    end



    respond_to do |format|
      if @ballot.save
        format.html { redirect_to @ballot.poll, notice: 'Ballot was successfully submitted.' }

      else
        format.html { redirect_to @ballot.poll, notice: @ballot.errors.full_messages.join(' ') }

      end
    end
  end









  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def ballot_params
      params.permit(:name)
    end

end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :set_poll, only: [:show, :edit, :update, :destroy]

  # GET /polls
  # GET /polls.json
  def index
    @polls = Poll.all
  end

  # GET /polls/1
  # GET /polls/1.json
  def show
    @ballot = Ballot.new

    # Don't try and calculate winner on a poll with no ballots
    if @poll.ballots.present?
      @winner = InstantRunoff.new(@poll).winner
    end
  end

  # GET /polls/new
  def new
    @poll = Poll.new
  end

  # GET /polls/1/edit
  def edit
  end

  # POST /polls
  # POST /polls.json
  def create
    @poll = Poll.new(poll_params)

    # declare variable with array from form
    options_param = params[:options]

    # map array from form to array of options in the database
    @poll.options = options_param.map do |o|
      Option.create(name: o) #create a row in the Options table with name == 'o' and poll_id the id of @poll
    end

    respond_to do |format|
      if @poll.save
        format.html { redirect_to @poll, notice: 'Poll was successfully created.' }
        format.json { render :show, status: :created, location: @poll }
      else
        format.html { render :new }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /polls/1
  # PATCH/PUT /polls/1.json
  def update
    respond_to do |format|
      if @poll.update(poll_params)
        format.html { redirect_to @poll, notice: 'Poll was successfully updated.' }
        format.json { render :show, status: :ok, location: @poll }
      else
        format.html { render :edit }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /polls/1
  # DELETE /polls/1.json
  def destroy
    @poll.destroy
    respond_to do |format|
      format.html { redirect_to polls_url, notice: 'Poll was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poll
      @poll = Poll.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poll_params
      params.require(:poll).permit(:title, :voting_method, :options, :blind)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VoteCounter</title>
    <%= csrf_meta_tags %>



    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "jquery", 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
    <%= render "shared/navbar" %>
    <div class= 'wrapper'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/polls/_form.html.erb
<%= form_with(model: poll, local: true) do |form| %>
  <% if poll.errors.any? %>
    <div class="error-explanation">
      <h2><%= pluralize(poll.errors.count, "error") %> prohibited this poll from being saved:</h2>

      <ul>
      <% poll.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class = 'form'>
    <div class="form__field">
      <%= form.label :title, 'Question:', class: 'form__label' %>
      <%= form.text_field :title, id: :poll_title, required:true%>
    </div>

    <div class = "form__field">
      <%= form.label :options, 'Options:', class: 'form__label' %>
      <div id="poll_options">
        <%= render 'poll_option' %>
        <%= render 'poll_option' %>
        <%= render 'poll_option' %>
      </div>
    </div>

    <button type='button' id="addNewOption" class = 'btn btn--new-option'>Add New Option</button>

    <div class="form__field form__field--row">
      <%= form.label :blind , 'Anonymous?'%>
      <%= form.check_box :blind, id: :poll_blind %>
    </div>

    <div>
      <%= form.submit %>
    </div>
  </div>
<% end %>

<div style="display: none;" id="new_option_form">
    <%= render partial: "poll_option", locals: {poll: false} %>
</div>

<script>
  document.getElementById('addNewOption').addEventListener('click', function() {
    $("#poll_options").append($("#new_option_form").html())
  });
</script>

app/views/polls/_poll_option.html.erb
<div class="form__field form__field--row">
     <!-- <%= label_tag "Option" %> -->

     <%= text_field_tag "options[]", nil, required:true %>

     <button type='button' onclick="document.getElementById('poll_options').removeChild(this.parentNode);" class="btn btn--remove" >X</button>

</div>

app/views/polls/edit.html.erb
<h1>Editing Poll</h1>

<%= render 'form', poll: @poll %>

<%= link_to 'Show', @poll %> |
<%= link_to 'Back', polls_path %>

app/views/polls/index.html.erb
<p id="notice"><%= notice %></p>


<div style = 'display: flex'>
  <h1>Explore Polls</h1>

  <%= link_to new_poll_path do %>
    <button class = 'btn btn--new-poll'>
       <span> New Poll </span>
     </button>
  <% end %>
</div>

<div class = 'display-polls'>
  <% @polls.each do |poll| %>
    <%= link_to poll do %>
      <div class = 'display-polls__poll'>
        <span class = 'display-polls__poll-title'> <%= poll.title %> </span>
      </div>
    <% end %>
  <% end %>


</div>

app/views/polls/new.html.erb
<div class = wrapper>
  <div class = 'wrapper__box wrapper__box--heading'>
    <h1>New Poll</h1>
    <%= render 'form', poll: @poll %>
  </div>
</div>

app/views/polls/show.html.erb
<div class = 'wrapper__box wrapper__box--heading'>

  <p id="notice"><%= notice %></p>

  <h1>
    <%= @poll.title %>
  </h1>

  <% if @poll.blind %>
    <p> (This poll is anonymous.) </p>
  <% else %>
    <p> (This poll is not anonymous.) </p>
  <% end %>

  <%= form_with(local: true) do |form| %>
    <div class = 'form'>

      <% unless @poll.blind %>
        <div class="form__field">
          <%= form.label :name, 'Name:', class: 'form__label' %>
          <%= form.text_field :name, id: :ballot_name, required:true %>
        </div>
      <% end %>

      <% @poll.options.each do |option| %>
          <div id = 'Rank' class = 'form__field form__field--row'>
              <%= form.label :rank_score, option.name, class: 'form__label'%>
              <%= form.select option.name + '_score', options_for_select((1..@poll.options.count)), class: 'form__arrow' %>
          </div>
      <%end%>

      <button class = 'btn'>Vote</button>
    </div>
  <% end %>
</div>

<% if @poll.ballots.present? %>
  <div class = 'wrapper__box '>

    <p>
      <strong> Winner (Instant-runoff):  </strong>
      <%= @winner%>
    </p>

    <p>
      <strong> Number of votes submitted:  </strong>
      <%= @poll.ballots.count %>
    </p>

    <br><br>

    <% unless @poll.blind %>
      <strong> Ballots:  </strong>

      <br><br>

      <table>
        <tr>
          <th></th>
            <% @poll.options.each do |option| %>
              <th>
                <%= option.name %>
              </th>
            <% end %>
        </tr>

        <% @poll.ballots.each do |ballot| %>
          <tr>
            <th> <%= ballot.name %> </th>
            <% ballot.ranks.each do |rank| %>
              <td> <%= rank.score %> </td>
            <% end %>
          </tr>
        <% end %>
      </table>

      <% end %>
    </div>
  <% end %>

app/views/shared/_navbar.html.erb
<!-- Topbar View  -->


<div class ='navbar'>
  <div class = 'navbar__tab'>
    <%= link_to 'Polls', '/polls' %>
  </div>

  <div class = 'navbar__tab'>
    <%= link_to 'New Poll', '/polls/new' %>
  </div>



</div>

app/views/shared/_topbar.html.erb
<!-- Topbar View  -->


<div id='topbar'>
  <div class = 'tab'>
    <%= link_to 'Polls', '/polls' %>
  </div>

  <div class = 'tab'>
    <%= link_to 'New Poll', '/polls/new' %>
  </div>

  

</div>